enable-magisk-update = false
parallel-jobs = 3

patches-version = "dev" # 'latest', 'dev', or a version number. default: "latest"
cli-version = "dev"       # 'latest', 'dev', or a version number. default: "latest"

# ReVanced Morphe
[YouTube-Morphe]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "MorpheApp/morphe-patches"
integrations-source = "MorpheApp/revanced-integrations"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe ReVanced"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Visual preferences icons' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Enable debug logging' 'Theme'"
patcher-args = """\
  -Ochange-package-name=app.rvx.android.youtube \
  """


# ReVanced Extended
[YouTube-Extended]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Visual preferences icons' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Enable debug logging' 'Theme'"
patcher-args = """\
  -Ochange-package-name=app.rvx.android.youtube \
  """

[YT-Music-Extended]
app-name = "YT-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Enable debug logging'"
patcher-args = """\
  -Ochange-package-name=com.google.android.apps.youtube.music \
  """

# ReVanced
[YouTube-Revanced]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "ReVanced/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Visual preferences icons' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Enable debug logging' 'Theme'"
patcher-args = """\
  -Ochange-package-name=app.revanced.android.youtube \
  """

[YT-Music-Revanced]
app-name = "YT-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "ReVanced/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Enable debug logging'"
patcher-args = """\
  -Ochange-package-name=app.revanced.android.youtube.music \
  """

#[Reddit-Extended]
#app-name = "Reddit" 
#apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
#uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
#patches-source = "inotia00/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
#cli-source = "inotia00/revanced-cli"
#rv-brand = "ReVanced Extended"
#arch = "arm64-v8a"
#build-mode = "apk"
#excluded-patches = "'Enable debug logging'"

[Spotify]
app-name = "Spotify" 
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
patches-source = "ReVanced/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced"
arch = "arm64-v8a"
build-mode = "apk"
excluded-patches = "'Enable debug logging'"
