enable-magisk-update = false
parallel-jobs = 2

# ReVanced
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
arch = "arm64-v8a"
build-mode = "apk"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"

[YT-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
build-mode = "apk"

# ReVanced Extended by anddea
[YouTube-anddea]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
arch = "arm64-v8a"
build-mode = "apk"
excluded-patches = "'Custom Shorts action buttons' 'Force player buttons background'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"

[YT-Music-anddea]
app-name = "YT Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Disable music video in album' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"

# Morphe
[YouTube-Morphe]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
build-mode = "apk"

[YT-Music-Morphe]
app-name = "YT Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
build-mode = "apk"
